language: node_js
os: linux
node_js: lts/*
cache:
  yarn: true
before_script:
- yarn
- yarn list
script: bash ./ci-test.sh
after_success:
- yarn global add travis-deploy-once
- travis-deploy-once "yarn semantic-release"
