// flow-typed signature: ef2857ffdf1f0e7385bcce8c95728f4d
// flow-typed version: <<STUB>>/css-modules-loader-core2_v^0.0.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'css-modules-loader-core2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'css-modules-loader-core2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'css-modules-loader-core2/lib/async/file-system-loader' {
  declare module.exports: any;
}

declare module 'css-modules-loader-core2/lib/async/index' {
  declare module.exports: any;
}

declare module 'css-modules-loader-core2/lib/async/parser' {
  declare module.exports: any;
}

declare module 'css-modules-loader-core2/lib/index' {
  declare module.exports: any;
}

declare module 'css-modules-loader-core2/lib/sync/file-system-loader' {
  declare module.exports: any;
}

declare module 'css-modules-loader-core2/lib/sync/index' {
  declare module.exports: any;
}

declare module 'css-modules-loader-core2/lib/sync/parser' {
  declare module.exports: any;
}

declare module 'css-modules-loader-core2/sync' {
  declare module.exports: any;
}

// Filename aliases
declare module 'css-modules-loader-core2/lib/async/file-system-loader.js' {
  declare module.exports: $Exports<'css-modules-loader-core2/lib/async/file-system-loader'>;
}
declare module 'css-modules-loader-core2/lib/async/index.js' {
  declare module.exports: $Exports<'css-modules-loader-core2/lib/async/index'>;
}
declare module 'css-modules-loader-core2/lib/async/parser.js' {
  declare module.exports: $Exports<'css-modules-loader-core2/lib/async/parser'>;
}
declare module 'css-modules-loader-core2/lib/index.js' {
  declare module.exports: $Exports<'css-modules-loader-core2/lib/index'>;
}
declare module 'css-modules-loader-core2/lib/sync/file-system-loader.js' {
  declare module.exports: $Exports<'css-modules-loader-core2/lib/sync/file-system-loader'>;
}
declare module 'css-modules-loader-core2/lib/sync/index.js' {
  declare module.exports: $Exports<'css-modules-loader-core2/lib/sync/index'>;
}
declare module 'css-modules-loader-core2/lib/sync/parser.js' {
  declare module.exports: $Exports<'css-modules-loader-core2/lib/sync/parser'>;
}
declare module 'css-modules-loader-core2/sync.js' {
  declare module.exports: $Exports<'css-modules-loader-core2/sync'>;
}
