// flow-typed signature: b8076b28b2330f2e66655ad4f417bb6f
// flow-typed version: <<STUB>>/cultureamp-style-guide_v^10.0.2/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cultureamp-style-guide'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cultureamp-style-guide' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cultureamp-style-guide/components/Icon/Demo' {
  declare module.exports: any;
}

declare module 'cultureamp-style-guide/components/Icon/Icon' {
  declare module.exports: any;
}

declare module 'cultureamp-style-guide/components/Icon/index' {
  declare module.exports: any;
}

declare module 'cultureamp-style-guide/components/NavigationBar/components/Badge' {
  declare module.exports: any;
}

declare module 'cultureamp-style-guide/components/NavigationBar/components/Link' {
  declare module.exports: any;
}

declare module 'cultureamp-style-guide/components/NavigationBar/components/Menu' {
  declare module.exports: any;
}

declare module 'cultureamp-style-guide/components/NavigationBar/components/Tooltip' {
  declare module.exports: any;
}

declare module 'cultureamp-style-guide/components/NavigationBar/index' {
  declare module.exports: any;
}

declare module 'cultureamp-style-guide/components/NavigationBar/NavigationBar' {
  declare module.exports: any;
}

declare module 'cultureamp-style-guide/util/error' {
  declare module.exports: any;
}

declare module 'cultureamp-style-guide/util/svg-sprite' {
  declare module.exports: any;
}

declare module 'cultureamp-style-guide/webpack/babel.config' {
  declare module.exports: any;
}

declare module 'cultureamp-style-guide/webpack/elmSvgAssetLoader' {
  declare module.exports: any;
}

declare module 'cultureamp-style-guide/webpack/index' {
  declare module.exports: any;
}

declare module 'cultureamp-style-guide/webpack/svgo.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cultureamp-style-guide/components/Icon/Demo.js' {
  declare module.exports: $Exports<'cultureamp-style-guide/components/Icon/Demo'>;
}
declare module 'cultureamp-style-guide/components/Icon/Icon.js' {
  declare module.exports: $Exports<'cultureamp-style-guide/components/Icon/Icon'>;
}
declare module 'cultureamp-style-guide/components/Icon/index.js' {
  declare module.exports: $Exports<'cultureamp-style-guide/components/Icon/index'>;
}
declare module 'cultureamp-style-guide/components/NavigationBar/components/Badge.js' {
  declare module.exports: $Exports<'cultureamp-style-guide/components/NavigationBar/components/Badge'>;
}
declare module 'cultureamp-style-guide/components/NavigationBar/components/Link.js' {
  declare module.exports: $Exports<'cultureamp-style-guide/components/NavigationBar/components/Link'>;
}
declare module 'cultureamp-style-guide/components/NavigationBar/components/Menu.js' {
  declare module.exports: $Exports<'cultureamp-style-guide/components/NavigationBar/components/Menu'>;
}
declare module 'cultureamp-style-guide/components/NavigationBar/components/Tooltip.js' {
  declare module.exports: $Exports<'cultureamp-style-guide/components/NavigationBar/components/Tooltip'>;
}
declare module 'cultureamp-style-guide/components/NavigationBar/index.js' {
  declare module.exports: $Exports<'cultureamp-style-guide/components/NavigationBar/index'>;
}
declare module 'cultureamp-style-guide/components/NavigationBar/NavigationBar.js' {
  declare module.exports: $Exports<'cultureamp-style-guide/components/NavigationBar/NavigationBar'>;
}
declare module 'cultureamp-style-guide/index' {
  declare module.exports: $Exports<'cultureamp-style-guide'>;
}
declare module 'cultureamp-style-guide/index.js' {
  declare module.exports: $Exports<'cultureamp-style-guide'>;
}
declare module 'cultureamp-style-guide/util/error.js' {
  declare module.exports: $Exports<'cultureamp-style-guide/util/error'>;
}
declare module 'cultureamp-style-guide/util/svg-sprite.js' {
  declare module.exports: $Exports<'cultureamp-style-guide/util/svg-sprite'>;
}
declare module 'cultureamp-style-guide/webpack/babel.config.js' {
  declare module.exports: $Exports<'cultureamp-style-guide/webpack/babel.config'>;
}
declare module 'cultureamp-style-guide/webpack/elmSvgAssetLoader.js' {
  declare module.exports: $Exports<'cultureamp-style-guide/webpack/elmSvgAssetLoader'>;
}
declare module 'cultureamp-style-guide/webpack/index.js' {
  declare module.exports: $Exports<'cultureamp-style-guide/webpack/index'>;
}
declare module 'cultureamp-style-guide/webpack/svgo.config.js' {
  declare module.exports: $Exports<'cultureamp-style-guide/webpack/svgo.config'>;
}
